import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :blogz, BlogzWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Setting primary domains, needs to be done at compile time for router host matching
# Feel free to change thes for your app
config :blogz,
  primary_domains: [
    System.get_env("BLOGZ_PRIMARY_DOMAIN", "localhost"),
    "www.#{System.get_env("BLOGZ_PRIMARY_DOMAIN", "localhost")}"
  ]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Blogz.Finch

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
